using MailKit.Net.Smtp;
using MimeKit;

namespace CoopMonitor.API.Services.Notifications;

public class EmailService : INotificationService
{
    private readonly IConfiguration _configuration;
    private readonly ILogger<EmailService> _logger;
    private readonly bool _isEnabled;
    private readonly string _host;
    private readonly int _port;
    private readonly bool _useSsl;
    private readonly string _username;
    private readonly string _password;
    private readonly string _fromEmail;
    private readonly string _toEmail;

    public EmailService(IConfiguration configuration, ILogger<EmailService> logger)
    {
        _configuration = configuration;
        _logger = logger;

        var section = _configuration.GetSection("Smtp");
        _isEnabled = section.GetValue<bool>("Enabled");
        _host = section["Host"] ?? "localhost";
        _port = section.GetValue<int>("Port", 587);
        _useSsl = section.GetValue<bool>("UseSsl", true);
        _username = section["Username"] ?? "";
        _password = section["Password"] ?? "";
        _fromEmail = section["FromEmail"] ?? "noreply@coop.local";
        _toEmail = section["ToEmail"] ?? "";
    }

    public async Task SendMessageAsync(string message)
    {
        // Для email обычные сообщения (не алерты) отправляем с темой Info
        await SendEmailInternalAsync("CoopMonitor Notification", message);
    }

    public async Task SendAlertAsync(string title, string details)
    {
        await SendEmailInternalAsync($"🚨 {title}", details);
    }

    private async Task SendEmailInternalAsync(string subject, string bodyText)
    {
        if (!_isEnabled) return;
        if (string.IsNullOrEmpty(_toEmail))
        {
            _logger.LogWarning("Email notifications enabled but ToEmail is empty.");
            return;
        }

        try
        {
            var message = new MimeMessage();
            message.From.Add(new MailboxAddress("CoopMonitor System", _fromEmail));
            message.To.Add(new MailboxAddress("Manager", _toEmail));
            message.Subject = subject;

            // Простая HTML разметка
            var htmlBody = $@"
                <div style='font-family: sans-serif; padding: 20px; border: 1px solid #ddd;'>
                    <h2 style='color: #2c3e50;'>{subject}</h2>
                    <p style='white-space: pre-wrap;'>{bodyText}</p>
                    <hr />
                    <small style='color: #999;'>Generated by CoopMonitor at {DateTime.UtcNow} UTC</small>
                </div>";

            message.Body = new TextPart("html") { Text = htmlBody };

            using var client = new SmtpClient();
            // Для демо отключаем проверку сертификатов (в проде убрать!)
            client.ServerCertificateValidationCallback = (s, c, h, e) => true;

            await client.ConnectAsync(_host, _port, _useSsl);

            if (!string.IsNullOrEmpty(_username))
            {
                await client.AuthenticateAsync(_username, _password);
            }

            await client.SendAsync(message);
            await client.DisconnectAsync(true);

            _logger.LogInformation("Email sent to {Email}: {Subject}", _toEmail, subject);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to send email.");
        }
    }
}