using RazorLight;
using System.Reflection;

namespace CoopMonitor.API.Services;

public class RazorReportGenerator : IReportGenerator
{
    private readonly IRazorLightEngine _engine;

    public RazorReportGenerator()
    {
        // Инициализация RazorLight для работы с внедренными ресурсами или строками.
        // Используем Builder для создания движка.
        _engine = new RazorLightEngineBuilder()
            // .UseEmbeddedResourcesProject(Assembly.GetEntryAssembly()) // Если шаблоны в ресурсах
            // Для упрощения MVP используем MemoryProject, где шаблоны задаются строками в коде,
            // либо можно подключить файловую систему.
            .UseMemoryCachingProvider()
            .Build();
    }

    public async Task<string> GenerateReportHtmlAsync<TModel>(string templateKey, TModel model)
    {
        // В реальном проекте шаблоны лежат в .cshtml файлах.
        // Здесь для демонстрации и надежности (чтобы не создавать кучу файлов) 
        // мы определим шаблон прямо в коде.

        string templateContent = GetTemplateContent(templateKey);

        return await _engine.CompileRenderStringAsync(templateKey, templateContent, model);
    }

    private string GetTemplateContent(string key)
    {
        // Простой HTML шаблон для ежедневного отчета
        if (key == "DailyReport")
        {
            // FIX: Добавлено @using System для доступа к DateTime.UtcNow
            return @"@using System
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 20px; }
        h1 { color: #2c3e50; }
        .card { border: 1px solid #ddd; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .metric-row { display: flex; justify-content: space-between; border-bottom: 1px solid #eee; padding: 10px 0; }
        .label { font-weight: bold; color: #555; }
        .value { color: #000; }
        .alert { color: red; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
    </style>
</head>
<body>
    <h1>@Model.Title</h1>
    <h3>@Model.HouseName | @Model.Date.ToString(""dd.MM.yyyy"")</h3>
    <p>Day of Cycle: @Model.DayOfCycle</p>

    <div class='card'>
        <h4>Production Metrics</h4>
        <div class='metric-row'>
            <span class='label'>Mortality Today:</span>
            <span class='value'>@Model.MortalityCount</span>
        </div>
        <div class='metric-row'>
            <span class='label'>Current Population:</span>
            <span class='value'>@Model.TotalPopulation</span>
        </div>
        <div class='metric-row'>
            <span class='label'>Feed Consumed:</span>
            <span class='value'>@Model.FeedConsumedKg.ToString(""F1"") kg</span>
        </div>
        <div class='metric-row'>
            <span class='label'>Water Consumed:</span>
            <span class='value'>@Model.WaterConsumedLiters.ToString(""F1"") L</span>
        </div>
    </div>

    <div class='card'>
        <h4>Climate Summary</h4>
        <div class='metric-row'>
            <span class='label'>Avg Temperature:</span>
            <span class='value'>@Model.AvgTemp.ToString(""F1"") °C</span>
        </div>
        <div class='metric-row'>
            <span class='label'>Avg Humidity:</span>
            <span class='value'>@Model.AvgHumidity.ToString(""F1"") %</span>
        </div>
        <div class='metric-row'>
            <span class='label'>Time in Range:</span>
            <span class='value'>@Model.TimeInRangePercent.ToString(""F1"") %</span>
        </div>
    </div>

    @if(Model.Alerts != null && Model.Alerts.Count > 0)
    {
        <div class='card' style='border-color: red;'>
            <h4 style='color: red;'>Alerts & Critical Events</h4>
            <ul>
                @foreach(var alert in Model.Alerts)
                {
                    <li class='alert'>@alert</li>
                }
            </ul>
        </div>
    }
    
    <footer>
        <small>Generated by CoopMonitor System at @DateTime.UtcNow</small>
    </footer>
</body>
</html>";
        }

        return "<h1>Template not found</h1>";
    }
}